version: '3.8'

services:
  bot:
    build: .
    container_name: tg_bot_tpartners
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Сохраняем базу данных между перезапусками
      - bot_data:/app/data
    networks:
      - bot_network

volumes:
  bot_data:
    driver: local

networks:
  bot_network:
    driver: bridge
